evaluate:
  num_gpus: 1
  conf_threshold: 0.0
  input_width: 640
  input_height: 640
dataset:
  test_data_sources:
    image_dir: /opt/nvidia/tools/tao-experiments/data/raw-data/val2017/
    json_file: /opt/nvidia/tools/tao-experiments/data/raw-data/annotations/instances_val2017.json
  num_classes: 27
  batch_size: 4
  workers: 8
  augmentation:
    fixed_padding: False
model:
  backbone: fan_small
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  num_select: 100
  dropout_ratio: 0.0
  dim_feedforward: 2048
