train:
  num_gpus: 1
  num_nodes: 1
  validation_interval: 1
  optim:
    lr_backbone: 2e-05
    lr: 2e-4
    lr_steps: [11]
    momentum: 0.9
  num_epochs: 100
dataset:
  train_data_sources:
    - image_dir: /opt/nvidia/tools/tao-experiments/data/raw-data/train2017/
      json_file: /opt/nvidia/tools/tao-experiments/data/raw-data/annotations/instances_train2017.json
  val_data_sources:
    - image_dir: /opt/nvidia/tools/tao-experiments/data/raw-data/val2017/
      json_file: /opt/nvidia/tools/tao-experiments/data/raw-data/annotations/instances_val2017.json
  num_classes: 27
  batch_size: 4
  workers: 12
  augmentation:
    # fixed_padding: False
    scales: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
    input_mean: [0.485, 0.456, 0.406]
    input_std: [0.229, 0.224, 0.225]
    horizontal_flip_prob: 0.5
    train_random_resize: [400, 500, 600]
    train_random_crop_min: 384
    train_random_crop_max: 600
    random_resize_max_size: 1333
    test_random_resize: 800
model:
  backbone: fan_small
  train_backbone: True
  pretrained_backbone_path: /opt/nvidia/tools/tao-experiments/dino/pretrained_dino_nvimagenet_vfan_small_hybrid_nvimagenet/fan_small_hybrid_nvimagenet.pth
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  num_select: 100
  dropout_ratio: 0.0
  dim_feedforward: 2048
