FROM nvcr.io/nvidia/tao/tao-toolkit:4.0.0-tf1.15.5  
#FROM nvcr.io/nvidia/tao/tao-toolkit:4.0.2-api

LABEL maintainer="anil<anil_kumar@solomon-3d.com>"

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install nvidia-tao
